# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rfw.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rfw.proto',
  package='cloudAssignment',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\trfw.proto\x12\x0f\x63loudAssignment\"|\n\x05query\x12\r\n\x05rfwID\x18\x01 \x01(\x05\x12\x15\n\rbenchmarkType\x18\x02 \x01(\t\x12\x16\n\x0eworkloadMetric\x18\x03 \x01(\t\x12\x11\n\tbatchUnit\x18\x04 \x01(\x05\x12\x0f\n\x07\x62\x61tchID\x18\x05 \x01(\x05\x12\x11\n\tbatchSize\x18\x06 \x01(\x05\"\\\n\x0cresponseData\x12\r\n\x05rfwID\x18\x01 \x01(\x05\x12\x0f\n\x07\x62\x61tchID\x18\x02 \x01(\x05\x12,\n\x07samples\x18\x03 \x03(\x0b\x32\x1b.cloudAssignment.sampleData\"\x97\x01\n\nsampleData\x12\x1d\n\x15\x63puUtilizationAverage\x18\x07 \x01(\t\x12\x18\n\x10networkInAverage\x18\x08 \x01(\t\x12\x19\n\x11networkOutAverage\x18\t \x01(\t\x12 \n\x18memoryUtilizationAverage\x18\n \x01(\t\x12\x13\n\x0b\x66inalTarget\x18\x0b \x01(\t2N\n\x03rfw\x12G\n\x0c\x66\x65tchDataFor\x12\x16.cloudAssignment.query\x1a\x1d.cloudAssignment.responseData\"\x00\x62\x06proto3'
)




_QUERY = _descriptor.Descriptor(
  name='query',
  full_name='cloudAssignment.query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rfwID', full_name='cloudAssignment.query.rfwID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='benchmarkType', full_name='cloudAssignment.query.benchmarkType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='workloadMetric', full_name='cloudAssignment.query.workloadMetric', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batchUnit', full_name='cloudAssignment.query.batchUnit', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batchID', full_name='cloudAssignment.query.batchID', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batchSize', full_name='cloudAssignment.query.batchSize', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=154,
)


_RESPONSEDATA = _descriptor.Descriptor(
  name='responseData',
  full_name='cloudAssignment.responseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rfwID', full_name='cloudAssignment.responseData.rfwID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batchID', full_name='cloudAssignment.responseData.batchID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='samples', full_name='cloudAssignment.responseData.samples', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=248,
)


_SAMPLEDATA = _descriptor.Descriptor(
  name='sampleData',
  full_name='cloudAssignment.sampleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpuUtilizationAverage', full_name='cloudAssignment.sampleData.cpuUtilizationAverage', index=0,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='networkInAverage', full_name='cloudAssignment.sampleData.networkInAverage', index=1,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='networkOutAverage', full_name='cloudAssignment.sampleData.networkOutAverage', index=2,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memoryUtilizationAverage', full_name='cloudAssignment.sampleData.memoryUtilizationAverage', index=3,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='finalTarget', full_name='cloudAssignment.sampleData.finalTarget', index=4,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=402,
)

_RESPONSEDATA.fields_by_name['samples'].message_type = _SAMPLEDATA
DESCRIPTOR.message_types_by_name['query'] = _QUERY
DESCRIPTOR.message_types_by_name['responseData'] = _RESPONSEDATA
DESCRIPTOR.message_types_by_name['sampleData'] = _SAMPLEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

query = _reflection.GeneratedProtocolMessageType('query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'rfw_pb2'
  # @@protoc_insertion_point(class_scope:cloudAssignment.query)
  })
_sym_db.RegisterMessage(query)

responseData = _reflection.GeneratedProtocolMessageType('responseData', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDATA,
  '__module__' : 'rfw_pb2'
  # @@protoc_insertion_point(class_scope:cloudAssignment.responseData)
  })
_sym_db.RegisterMessage(responseData)

sampleData = _reflection.GeneratedProtocolMessageType('sampleData', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEDATA,
  '__module__' : 'rfw_pb2'
  # @@protoc_insertion_point(class_scope:cloudAssignment.sampleData)
  })
_sym_db.RegisterMessage(sampleData)



_RFW = _descriptor.ServiceDescriptor(
  name='rfw',
  full_name='cloudAssignment.rfw',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=404,
  serialized_end=482,
  methods=[
  _descriptor.MethodDescriptor(
    name='fetchDataFor',
    full_name='cloudAssignment.rfw.fetchDataFor',
    index=0,
    containing_service=None,
    input_type=_QUERY,
    output_type=_RESPONSEDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RFW)

DESCRIPTOR.services_by_name['rfw'] = _RFW

# @@protoc_insertion_point(module_scope)
