# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rfw_pb2 as rfw__pb2


class rfwStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.fetchDataFor = channel.unary_unary(
                '/cloudAssignment.rfw/fetchDataFor',
                request_serializer=rfw__pb2.query.SerializeToString,
                response_deserializer=rfw__pb2.responseData.FromString,
                )


class rfwServicer(object):
    """Missing associated documentation comment in .proto file."""

    def fetchDataFor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_rfwServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'fetchDataFor': grpc.unary_unary_rpc_method_handler(
                    servicer.fetchDataFor,
                    request_deserializer=rfw__pb2.query.FromString,
                    response_serializer=rfw__pb2.responseData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloudAssignment.rfw', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class rfw(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def fetchDataFor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloudAssignment.rfw/fetchDataFor',
            rfw__pb2.query.SerializeToString,
            rfw__pb2.responseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
